name: "Restore Allure History"
description: "Fetches history.jsonl from the orphan branch"
runs:
  using: "composite"
  steps:
    - name: Checkout History Branch
      uses: actions/checkout@v4
      continue-on-error: true
      with:
        ref: allure-history
        path: allure-history-branch

    - name: Restore History JSONL
      shell: bash
      run: |
        mkdir -p tests/reports
        if [ -f "allure-history-branch/history.jsonl" ]; then
          cp allure-history-branch/history.jsonl tests/reports/history.jsonl
          echo "History restored successfully."
          # Count lines to show how many runs are in history
          lines=$(wc -l < tests/reports/history.jsonl)
          echo "History contains $lines run(s)"
        else
          echo "No history found (first run?), skipping restoration."
        fi