name: "Generate Allure Report"
description: "Generates Allure 3 report with history"
inputs:
  github_run_number:
    required: true
  github_run_id:
    required: true
  github_repository:
    required: true
  github_repository_owner:
    required: true
  github_repo_name:
    required: true
runs:
  using: "composite"
  steps:
    - name: Create Allure Config File
      if: always()
      shell: bash
      run: |
        # Create config file in project root
        cat > allure.config.json << 'EOF'
        {
          "name": "Bank Management Test Report",
          "output": "./tests/reports/allure-report",
          "historyPath": "./tests/reports/history.jsonl",
          "historyLimit": 20
        }
        EOF
        echo "Config file created"
        cat allure.config.json

    - name: Add Allure Metadata
      if: always()
      shell: bash
      run: |
        cat > tests/reports/allure-results/environment.properties << EOF
        Project=Bank Management System
        Environment=GitHub Actions (CI)
        Executor=GitHub Actions
        Build.Number=${{ inputs.github_run_number }}
        Build.URL=https://github.com/${{ inputs.github_repository }}/actions/runs/${{ inputs.github_run_id }}
        Repository=${{ inputs.github_repository }}
        Branch=${GITHUB_REF##*/}
        Commit=${GITHUB_SHA:0:7}
        EOF
        
        cat > tests/reports/allure-results/executor.json << EOF
        {
          "name": "GitHub Actions",
          "type": "github",
          "url": "https://github.com/${{ inputs.github_repository }}",
          "buildOrder": ${{ inputs.github_run_number }},
          "buildName": "Run #${{ inputs.github_run_number }}",
          "buildUrl": "https://github.com/${{ inputs.github_repository }}/actions/runs/${{ inputs.github_run_id }}",
          "reportName": "Allure Report"
        }
        EOF

    - name: Generate Allure 3 Report
      if: always()
      shell: bash
      run: |
        rm -rf tests/reports/allure-report
        
        if [ -f "tests/reports/history.jsonl" ]; then
          echo "History file found with $(wc -l < tests/reports/history.jsonl) run(s)"
        else
          echo "No history file found (first run)"
        fi
        
        allure generate tests/reports/allure-results --config allure.config.json
        
        echo "Allure 3 report generated successfully"