name: "Generate Allure Report"
description: "Generates Allure 3 report with history"
inputs:
  github_run_number:
    required: true
  github_run_id:
    required: true
  github_repository:
    required: true
  github_repository_owner:
    required: true
  github_repo_name:
    required: true
runs:
  using: "composite"
  steps:
    - name: Add Allure Metadata
      if: always()
      shell: bash
      run: |
        # Create environment.properties for Allure
        cat > tests/reports/allure-results/environment.properties << EOF
        Project=Bank Management System
        Environment=GitHub Actions (CI)
        Executor=GitHub Actions
        Build.Number=${{ inputs.github_run_number }}
        Build.URL=https://github.com/${{ inputs.github_repository }}/actions/runs/${{ inputs.github_run_id }}
        Repository=${{ inputs.github_repository }}
        Branch=${GITHUB_REF##*/}
        Commit=${GITHUB_SHA:0:7}
        EOF
        
        # Create executor.json for Allure
        cat > tests/reports/allure-results/executor.json << EOF
        {
          "name": "GitHub Actions",
          "type": "github",
          "url": "https://github.com/${{ inputs.github_repository }}",
          "buildOrder": ${{ inputs.github_run_number }},
          "buildName": "Run #${{ inputs.github_run_number }}",
          "buildUrl": "https://github.com/${{ inputs.github_repository }}/actions/runs/${{ inputs.github_run_id }}",
          "reportName": "Allure Report"
        }
        EOF

    - name: Create Allure 3 Config with Single File
      if: always()
      shell: bash
      run: |
        # Create Allure 3 config with Awesome plugin and single-file
        cat > allurerc.json << EOF
        {
          "name": "Bank Management Test Report",
          "output": "./tests/reports/allure-report",
          "historyPath": "./tests/reports/history.jsonl",
          "historyLimit": 20,
          "plugins": {
            "awesome": {
              "options": {
                "singleFile": true,
                "reportLanguage": "en"
              }
            }
          }
        }
        EOF

    - name: Generate Allure 3 Report
      if: always()
      shell: bash
      run: |
        # Remove old report if exists
        rm -rf tests/reports/allure-report
        
        # Generate report using Allure 3 with config
        allure generate tests/reports/allure-results --config allurerc.json
        
        echo "Allure 3 report generated with Awesome plugin (single-file mode)"