name: "Generate Allure Report"
description: "Generates Allure 3 report with history"
inputs:
  github_run_number:
    required: true
  github_run_id:
    required: true
  github_repository:
    required: true
  github_repository_owner:
    required: true
  github_repo_name:
    required: true
runs:
  using: "composite"
  steps:
    - name: Add Metadata
      if: always()
      shell: bash
      run: |
        cat > tests/reports/allure-results/environment.properties << EOF
        Project=Bank Management System
        Environment=GitHub Actions (CI)
        Build.Number=${{ inputs.github_run_number }}
        Build.URL=https://github.com/${{ inputs.github_repository }}/actions/runs/${{ inputs.github_run_id }}
        Repository=${{ inputs.github_repository }}
        Branch=${GITHUB_REF##*/}
        Commit=${GITHUB_SHA:0:7}
        EOF

    # 2. Generate Report (Modified)
    - name: Generate Report
      if: always()
      shell: bash
      run: |
        rm -rf tests/reports/allure-report
        
        # --- TRICK: Inject 'singleFile: true' just for this CI run ---
        # This finds "options:" and adds "singleFile: true" on the next line
        sed -i 's/options:/options:\n      singleFile: true/' allurerc.yml
        
        # Verify the injection (for debugging)
        # grep -A 2 "options:" allurerc.yml

        # Generate using the now-modified config
        allure generate tests/reports/allure-results --config allurerc.yml
        
        echo "Single-file Allure 3 report generated using modified allurerc.yml"