from tests.api.utils.validators import Any, Regex # Import Regex

class ExpectedResponse:

    @staticmethod
    def expected_response_create_account():
        return {
            "account_id": Regex(r"^\d{7}$", "7-Digit ID"),
            # Ensure date format is YYYY-MM-DD
            "date_opened": Regex(r"^\d{4}-\d{2}-\d{2}$", "YYYY-MM-DD Date"),
            "message": "Account created successfully"
        }

    @staticmethod
    def expected_response_update_account():
        return {
            "message": "Account updated successfully"
        }

    @staticmethod
    def expected_response_delete_account():
        return {
            "message": "Account deleted successfully"
        }

    @staticmethod
    def expected_response_get_account_create(row, account_id):
        return {
            "account_id": account_id,
            "account_holder_name": row["account_holder_name"],
            "dob": row["dob"],
            "gender": row["gender"],
            "email": row["email"],
            "phone": row["phone"],
            "address": row["address"],
            "zip_code": row["zip_code"],
            "account_type": row["account_type"],
            "balance": float(row["balance"]),
            # We expect a date string, but since it's generated by backend,
            # we can't match it against CSV accurately unless we capture it from create response.
            # For now, asserting it exists and is a string is safe.
            "date_opened": Regex(r"^\d{4}-\d{2}-\d{2}$", "YYYY-MM-DD Date"),
            "status": row["status"],
            "services": row["services"],
            "marketing_opt_in": row["marketing_opt_in"].lower() == "true",
            "agreed_to_terms": True
        }

    @staticmethod
    def expected_response_get_account_update(row, account_id):
        return {
            "account_id": account_id,
            "account_holder_name": row["updated_account_holder_name"],
            "dob": row["updated_dob"],
            "gender": row["updated_gender"],
            "email": row["updated_email"],
            "phone": row["updated_phone"],
            "address": row["updated_address"],
            "zip_code": row["updated_zip_code"],
            "account_type": row["updated_account_type"],
            "balance": float(row["updated_balance"]),
            # Date should NOT change on update, so it should still be a string
            "date_opened": Regex(r"^\d{4}-\d{2}-\d{2}$", "YYYY-MM-DD Date"),
            "status": row["updated_status"],
            "services": row["updated_services"],
            "marketing_opt_in": row["updated_marketing_opt_in"].lower() == "true",
            "agreed_to_terms": True
        }