Project=Bank Management System
Environment=GitHub Actions (CI)
Build.Number=311
Build.URL=https://github.com/harshamaiya99/bank-management-system/actions/runs/32516621138
Repository=harshamaiya99/bank-management-system
Branch=main
Commit=50d0b8c
