Project=Bank Management System
Environment=GitHub Actions (CI)
Build.Number=291
Build.URL=https://github.com/harshamaiya99/bank-management-system/actions/runs/24309212340
Repository=harshamaiya99/bank-management-system
Branch=merge
Commit=7411e69
