Project=Bank Management System
Environment=GitHub Actions (CI)
Build.Number=307
Build.URL=https://github.com/harshamaiya99/bank-management-system/actions/runs/30121887079
Repository=harshamaiya99/bank-management-system
Branch=main
Commit=50d0b8c
