name: "Run Backend and Tests"
description: "Starts FastAPI and runs Pytest"
runs:
  using: "composite"
  steps:

    - name: Start Backend Server
      shell: bash
      run: |
        # Start uvicorn in the background using '&'
        uvicorn main:app --app-dir src/backend --host 127.0.0.1 --port 9000 &
        echo "Waiting for server to start..."
        sleep 5  # Give it a moment to initialize the DB

    - name: Run Tests
      shell: bash
      env:
        BASE_URL: http://127.0.0.1:9000
      run: |
        # Added -s to ensure Karate/Maven logs from the Python wrapper are visible in the console
        pytest tests/ --alluredir=allure-results -s