name: "Run Backend and Tests"
description: "Starts FastAPI and runs Pytest"
runs:
  using: "composite"
  steps:
    - name: Start FastAPI Backend
      shell: bash
      run: |
        nohup uvicorn main:app --app-dir src/backend --host 127.0.0.1 --port 9000 > server.log 2>&1 &
        echo "Waiting for server to start..."
        sleep 5

    - name: Run Tests
      shell: bash
      env:
        BASE_URL: http://127.0.0.1:9000
      run: |
        pytest tests/ --alluredir=allure-results