name: "Run Backend, Frontend and Tests"
description: "Starts FastAPI & Vite, then runs Pytest"
runs:
  using: "composite"
  steps:
    # --- Start Backend ---
    - name: Start Backend Server
      shell: bash
      run: |
        echo "Starting Uvicorn..."
        uvicorn main:app --app-dir src/backend --host 127.0.0.1 --port 9000 &

    # --- Start Frontend ---
    - name: Start Frontend Server
      shell: bash
      working-directory: src/frontend
      run: |
        echo "Starting Vite..."
        npm run dev -- --port 5173 &

    # --- Wait for Services ---
    - name: Wait for Services to initialize
      shell: bash
      run: |
        echo "Waiting for services to start..."
        sleep 10

    # --- Run Tests ---
    - name: Run Tests
      shell: bash
      env:
        BASE_URL: http://127.0.0.1:9000
        VITE_BASE_URL: http://localhost:5173
        # CI-specific environment variables for Allure
        TEST_ENV: CI
        CI_BUILD: "true"
        BUILD_NUMBER: ${{ github.run_number }}
        GIT_BRANCH: ${{ github.ref_name }}
        TESTER_NAME: "GitHub Actions"
      run: |
        echo "Running API and UI Tests..."
        pytest tests -s